name: Build & Release Tori

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Build Core version
        run: mvn -B package -DskipTests --file pom.xml

      - name: Build Full DAVE version
        run: mvn -B package -P dave-build -DskipTests --file pom.xml

      # Upload đích danh các file vào Release
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            tori-api/target/tori-api-*.jar
            tori-server/target/tori-server-core.jar
            tori-server/target/tori-server-full-dave.jar
            tori-extension-dave/target/tori-extension-dave-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}